name: CI

on:
  push:
    branches: [ new ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ new ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        build: [ linux ]
        include:
          - build: linux
            os: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install pipenv
      run: pip install pipenv
    - name: Run test
      run: |
          sudo apt update
          sudo apt install nvidia-cuda-toolkit
          sudo apt install nvidia-cudnn
          pipenv install
          make ci
