name: CI

on:
  push:
    branches: [ new ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ new ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      matrix:
        build: [ linux ]
        include:
          - build: linux
            os: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Install apt packages
      run: |
          #---- ** 'cuda-11-7'
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
          sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
          sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
          sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
          #----
          sudo apt update
          sudo apt install nvidia-cuda-toolkit
          #---- ** primus852/cuda_11.7_installation_on_Ubuntu_22.04 - https://gist.github.com/primus852/b6bac167509e6f352efb8a462dcf1854
          sudo apt install cuda-11-7
          wget https://developer.download.nvidia.com/compute/redist/cudnn/v8.5.0/local_installers/11.7/cudnn-linux-x86_64-8.5.0.96_cuda11-archive.tar.xz
          tar xvf cudnn-linux-x86_64-8.5.0.96_cuda11-archive.tar.xz
          sudo cp -P cudnn-linux-x86_64-8.5.0.96_cuda11-archive/include/cudnn.h /usr/local/cuda-11.7/include
          sudo cp -P cudnn-linux-x86_64-8.5.0.96_cuda11-archive/lib/libcudnn* /usr/local/cuda-11.7/lib64/
          sudo chmod a+r /usr/local/cuda-11.7/lib64/libcudnn*
          #----
          sudo apt install unrar
    - name: Install pipenv
      run: pip install pipenv
    - name: Run test 🧪🧪🧪🧪
      run: make ci
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          log.txt
          output.zip
